### ISSUE TITLE
Adapt pre-existing Twine story format to also export the json config needed for SMS games

### ISSUE THREAD

**Issue by jonuy** [DoSomething/intertwine#9]

**Comment by tongxiang** [comment]
So you'd like for a pre-existing game format (i.e. one that will support the normal play-through of Twine games) to **also** export the JSON config? (Perhaps somewhere on that page, or on a new page?)

Is this what you're suggesting with this issue?

**Comment by jonuy** [comment]
That's initially what it was, but after looking into it more yesterday, it might just be easier to make it a completely separate process. There's a "View Proofing Copy" option in the editor view that exports a barebones text version of the story.

![screen shot 2015-01-29 at 10 12 29 am](https://cloud.githubusercontent.com/assets/696595/5959844/650fe640-a79f-11e4-94c6-fbf5ea816359.png)

It's something we could emulate and just tack on another option to that menu.

**Comment by tongxiang** [comment]
nice!
